# Generated by Django 5.0.4 on 2024-04-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_student_group_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_pair', models.IntegerField(help_text='Введите порядковый номер занятия (например, 1)')),
                ('start_pair', models.TimeField()),
                ('end_pair', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.CharField(help_text='Введите номер группы (например, 4443-100301D)', max_length=12),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='contact_email',
            field=models.EmailField(max_length=100),
        ),
    ]
