# Generated by Django 5.0.4 on 2024-04-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_rename_teacher_number_schedule_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
